name: build java-arm64
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "yolks:java_${{ matrix.tag }}-arm64"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - graalvm-EE
          - 8
          - 11
          - 16
          - 17
          - 21
          - 22
          - 23
          - 24

          - 8-jre
          - 11-jre
          - 16-jre
          - 17-jre
          - 21-jre
          - 22-jre
          - 23-jre
          - 24-jre

          - 17-graalvm
          - 21-graalvm
          - 22-graalvm
          - 23-graalvm
          - 24-graalvm

          - 17-graalvm-slim
          - 21-graalvm-slim
          - 22-graalvm-slim
          - 23-graalvm-slim
          - 24-graalvm-slim

          - 17-g-thanos
          - 21-g-thanos
          - 22-g-thanos
          - 23-g-thanos
          - 24-g-thanos
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "soapy7261"
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/soapy7261/yolks:java_${{ matrix.tag }}-arm64
